service: backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-ruby-layer
functions:
  whoami:
    handler: handler.whoami
    events:
      - http:
          path: ping
          method: get
          cors: true
  recipes:
    handler: handler.recipes
    events:
      - http:
          path: recipes
          method: get
          cors: true
