service: backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

functions:
  whoami:
    handler: handler.whoami
    events:
      - http:
          path: ping
          method: get
